package com.test.executorFramework;

public class ThreadLocalCustomerSharedVariable9 {
    
    public static void main(String[] args) {
        
        CustomerThread ct1= new CustomerThread("Ram");
        CustomerThread ct2= new CustomerThread("Sham");
        CustomerThread ct3= new CustomerThread("ghanShyam");
        CustomerThread ct4= new CustomerThread("parsuram");
        
        ct1.start();
        ct2.start();
        ct3.start();
        ct4.start();
    }

}

class CustomerThread extends Thread{
    
    static int custId=1000;
    
    public static ThreadLocal tl= new ThreadLocal(){
        
        @Override
        public Object initialValue()
        {
            return new Integer(custId++);
        }
    };
    
    public CustomerThread(String name)
    {
        super(name);
    }
    
    @Override
    public void run(){
        
        int value= (Integer)tl.get();
        System.out.println("current Thead Name : "+Thread.currentThread().getName()+" having unique Customer ID generated by ThreadLocal : " + value);
        try{
            Thread.sleep(2000);
        }catch(InterruptedException e)
        {
            System.out.println("Exception"+e.getLocalizedMessage());
        }
        System.out.println("current Thead Name : "+Thread.currentThread().getName()+" having Customer ID  generated by ThreadLocal: " + value);
    }
}
